version: 2
updates:
  # npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'Asia/Kolkata'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'npm'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      playwright:
        patterns:
          - '@playwright/*'
          - 'playwright*'
          - 'allure-*'
      types:
        patterns:
          - '@types/*'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'Asia/Kolkata'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'ci'
      include: 'scope'
